// Fetch POSTs
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const RESET_POSTS = 'RESET_POSTS';

// Fetch POST
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';

// Create POST
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

// Delete POST
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

// Update POST
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

// Fetch COMMENTs
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
export const RESET_COMMENTS = 'RESET_COMMENTS';

// Fetch COMMENT
export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_FAILURE = 'FETCH_COMMENT_FAILURE';

// Create COMMENT
export const CREATE_COMMENT = "CREATE_COMMENT";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

// Delete COMMENT
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";

// Update COMMENT
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILURE = "UPDATE_COMMENT_FAILURE";


// Location markers
export const FETCH_MARKERS = "FETCH_MARKERS";
export const FETCH_MARKERS_SUCCESS = "FETCH_MARKERS_SUCCESS";
export const FETCH_MARKERS_FAILURE = "FETCH_MARKERS_FAILURE";


// Fetch LEFTOVERS
export const FETCH_LEFTOVERS = 'FETCH_LEFTOVERS';
export const FETCH_LEFTOVERS_SUCCESS = 'FETCH_LEFTOVERS_SUCCESS';
export const FETCH_LEFTOVERS_FAILURE = 'FETCH_LEFTOVERS_FAILURE';
export const RESET_LEFTOVERS = 'RESET_LEFTOVERS';

// Fetch LEFTOVER
export const FETCH_LEFTOVER = 'FETCH_LEFTOVER';
export const FETCH_LEFTOVER_SUCCESS = 'FETCH_LEFTOVER_SUCCESS';
export const FETCH_LEFTOVER_FAILURE = 'FETCH_LEFTOVER_FAILURE';

// Create LEFTOVER
export const CREATE_LEFTOVER = "CREATE_LEFTOVER";
export const CREATE_LEFTOVER_SUCCESS = "CREATE_LEFTOVER_SUCCESS";
export const CREATE_LEFTOVER_FAILURE = "CREATE_LEFTOVER_FAILURE";

// Delete LEFTOVER
export const DELETE_LEFTOVER = "DELETE_LEFTOVER";
export const DELETE_LEFTOVER_SUCCESS = "DELETE_LEFTOVER_SUCCESS";
export const DELETE_LEFTOVER_FAILURE = "DELETE_LEFTOVER_FAILURE";

// Update LEFTOVER
export const UPDATE_LEFTOVER = "UPDATE_LEFTOVER";
export const UPDATE_LEFTOVER_SUCCESS = "UPDATE_LEFTOVER_SUCCESS";
export const UPDATE_LEFTOVER_FAILURE = "UPDATE_LEFTOVER_FAILURE";


// User
export const SET_USER = "SET_USER";